name: update

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - uses: actions/setup-python@v2
        with:
          python-version: 3.13

      - run: pip3 install -U -r requirements.txt
      - run: mkdocs gh-deploy --force
